### ISSUE TITLE
implement chat frontend into sidebar

### ISSUE THREAD

**Issue by tibotiber** [tibotiber/rd3#42]

**Comment by claudioantonio** [comment]
Hi @tibotiber , is the ideia to implement a chat that at each message arrival would update the charts based on the message text?
Or Would messages for each user be accumulated/consolidated in one single text content, like that 2 actual input texts, to charts update?

**Comment by tibotiber** [comment]
Hi @claudioantonio, it's been a while and I've lost a bit of context but yeah I think the idea was to demonstrate live charts on "less fake content". So for example the chat would replace the 2 inputs and each incoming message would update the charts.
